version: '3'
services:
    nginx:
        user: "root"
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www:rw
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
    php-fpm:
        user: "root"
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www:rw
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    php-cli:
        user: "root"
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www:rw
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    mysql:
        user: "1000"
        image: mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql:rw
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "3306:3306"
    redis:
        user: "root"
        image: redis
        ports:
            - "6379:6379"
    node:
        image: "node:16"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - "5174:5174"
        command: "npm run dev"
